services:
  orchmind_redis:
    image: bitnami/redis:latest
    container_name: orchmind_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    env_file:
      - .env
    volumes:
      - ./.docker/redis-data:/data
    networks:
      - orchmind-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
    orchmind-network:
        external: true
