services:
    orchmind_pg:
        container_name: orchmind_pg
        build:
            context: ./
            dockerfile: .dockerfile
        image: orchmind_pg:latest
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./.docker:/var/lib/postgresql/data
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        command: ["postgres", "-c", "wal_level=logical"]
        ports:
            - "5432:5432"
        networks:
            - orchmind-network
        healthcheck:
            test: ["CMD-SHELL", "PGPASSWORD=$${POSTGRES_PASSWORD} psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1;'"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

networks:
    orchmind-network:
        external: true
